// Copyright 2026 cloudeng llc. All rights reserved.
// Use of this source code is governed by the Apache-2.0
// license that can be found in the LICENSE file.

// Code generated by astest. DO NOT EDIT.

package tartvm_test

import (
	"testing"

	"cloudeng.io/cicd"
	"cloudeng.io/vms/vmstestutil"
)

func TestPoolAcquireExecRelease(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = poolConfig.Get(t.Name())
	vmstestutil.TestPoolAcquireExecRelease(t, cfg)
}

func TestPoolClose(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = poolConfig.Get(t.Name())
	vmstestutil.TestPoolClose(t, cfg)
}

func TestPoolConcurrentAcquire(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = poolConfig.Get(t.Name())
	vmstestutil.TestPoolConcurrentAcquire(t, cfg)
}

func TestPoolContextCancellation(t *testing.T) {
	var cfg vmstestutil.PoolTestConfig
	cicd.LongRunningTest(t, 1)
	cfg = poolConfig.Get(t.Name())
	vmstestutil.TestPoolContextCancellation(t, cfg)
}
